version: '3.2'
services:
  nexus-servers:
    image: sonatype/nexus3:3.25.1
    container_name: nexus
    restart: always
    privileged: true
    volumes:
      - ./data/:/nexus-data/
    ports:
      - 10081:8081
    networks:
      - nuts
 
networks:
  nuts:
    driver: bridge