version: '3.2'
services:
 
  gitlab:
#    image: gitlab/gitlab:13.11.2
    image: gitlab/gitlab-ce:12.9.2-ce.0
    hostname: 54.64.76.140
    container_name: gitlab
    restart: always
    privileged: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://54.64.76.140:10443'
        nginx['client_max_body_size'] = '800m'
        nginx['listen_port'] = 443
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/gitlab.crt"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/gitlab.key"
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
        nginx['ssl_session_cache'] = "builtin:1000  shared:SSL:10m"
        nginx['listen_addresses'] = ["0.0.0.0"]
        nginx['http2_enabled'] = true
        nginx['logrotate_frequency'] = "weekly"
        nginx['logrotate_rotate'] = 52
        nginx['logrotate_compress'] = "compress"
        nginx['logrotate_method'] = "copytruncate"
        nginx['logrotate_delaycompress'] = "delaycompress"
    volumes:
      - ./data/config:/etc/gitlab
      - ./data/ssl:/etc/ssl/certs/gitlab
      - ./data/logs:/var/log/gitlab
      - ./data/data:/var/opt/gitlab
    ports:
      - 10443:443
#      - 1080:80
    networks:
      - nuts
 
networks:
  nuts:
    driver: bridge